### ISSUE TITLE
Permalinks to dashboard state

### ISSUE THREAD

**Issue by ozten** [mozilla/kpi-dashboard#22]
Originally filed in https://github.com/nmalkin/kpi-dashboard/issues/19

You can already link to individual reports, but it would be helpful if you could link to a particular version of the report (e.g., with a certain date range, or segmentation, selected).

**Comment by kparlante** [comment]
@shane-tomlinson : you may not have much more time for dashboard hacking, but in case you do, this one might be a good one to take. I'm upgrading it to 4\* -- easier to share reports.
