### ISSUE TITLE
Bounce rate visualization

### ISSUE THREAD

**Issue by kparlante** [mozilla/kpi-dashboard#44]
Capture "bounce rate", which is % of users who open dialog once but then never use persona again.

We've compared total number of blobs to total number of /sign_in calls manually and estimate that its ~40%. We'd like to be tracking this over time, with train milestones. Also, we'll want this as the metric to optimize when we're doing A/B testing.

For this visualization, either we need the *-metrics data (the metrics that fuel the pentaho dashboard) or we need https://github.com/mozilla/browserid/issues/3306

**Comment by kparlante** [comment]
FWIW, I think this should be a Q2 goal to set us up for A/B testing, which was a stretch goal.

**Comment by kparlante** [comment]
@shane-tomlinson, @seanmonstar,

I'm working on adding the bounce rate to the dashboard (as a separate visualization and/or as the first step in the new user flow), and could use some feedback on the right way to recognize a "bounce". 

If we think about it in terms of the new user flow, we want to count the number of times the dialog is opened and then closed without the user going down a particular path (either the "new fallback user" path or some other path).

These are the cases that I was planning on _not_ interpreting as bounces:
- The user hits screen.set_password (this is our indication that the user is going down the path of creating a new fallback account)
- The user hits authenticate.enter_password (we recognize the fallback account and are prompting for a password)
- The user hits screen.pick_email (the user has a fallback or primary account)
- The user hits screen.provision_primary_user (the user is going down the path of authenticating with an IdP or identity bridge)
- The event list has staging_continuation (this user was waiting for email verification, so the user is on the new fallback user path)
- This may be redundant with the above, but if the user at some point gets an assertion_generated event, then clearly they are not "bouncing"
- If the user has number_emails, number_sites_signed_in, or number_sites_remembered > 0, then the user has used browserid before -- not a bounce

If I bring up a dialog from a fresh state and then close it, I get an event stream like the following:

window.dom_loading
xhr_complete.GET/wsapi/session_context
window.channel_established
screen.rp_info
screen.authenticate
user.can_interact
window.unload

And indeed, when I test out a query using the logic above (on recent data), I do see many blobs that have those events (perhaps without window.unload).

I also see a lot of blobs that don't quite look like that. Indeed, a full 10% of _all_ blobs have one event: window.unload. Another 1% have a different single event (xhr...user_creation_status, xhr...session_context, etc).

Data on the one event blobs: https://id.etherpad.mozilla.org/kpi-bounce-rate-data

Questions:
- Any thoughts about the one event blobs? Should we just go ahead and count these as bounces?
- Do the cases above sound about right? Do you think I'm missing anything?

cc: @ryanfeeley

**Comment by seanmonstar** [comment]
Sounds reasonable to me. The 1-event blobs sound scary...

**Comment by kparlante** [comment]
Added in #83, but full credit answer is to implement #60
