### ISSUE TITLE
Segment screen size by mobile/tablet/desktop

### ISSUE THREAD

**Issue by kparlante** [mozilla/kpi-dashboard#58]
@skinny97214 tells me she has the breakpoints...

**Comment by skinny97214** [comment]
@shane-tomlinson Can you give us the desktop/tablet to phone breakpoint?

**Comment by shane-tomlinson** [comment]
@skinny97214, @kparlante - 640px

**Comment by kparlante** [comment]
@skinny97214, @shane-tomlinson : I'll use <= 640px and >=1024px to segment into small, med, wide. 1024x768 is both the iPad landscape mode and (until very recently) the most common desktop size.
