### ISSUE TITLE
"New users per day" for Identity Bridging users

### ISSUE THREAD

**Issue by kparlante** [mozilla/kpi-dashboard#69]
Also applies to IdPs

Either place on same new_users_per_day graph or do a separate visualization

**Comment by shane-tomlinson** [comment]
@kparlante - do you have data from the KPI stream to get this?

**Comment by kparlante** [comment]
@shane-tomlinson : I think we can get both this and data for #60 and #70 from KPI data, but it does rely on the new_account flag to be accurate for IdP users. Here's a proposed query (a map method in couchdb):

```
function(doc) {
  var events = doc.event_stream.map(function(eventPair) {
    return eventPair[0];
  });

  if (doc.generalProgressSteps.indexOf('1 - Dialog shown') !== -1) {
    if (doc.generalProgressSteps.indexOf('2 - User engaged') === -1) {
        emit(doc.date, {"bounce":1});
    } else if (events.indexOf('assertion_generated') !== -1 ) {
      if (doc.newUserSteps.length !== 0) {
        emit(doc.date, {"fallback":1});
      } else if (doc.new_account && events.indexOf('screen.provision_primary_user') !== -1) {
        emit(doc.date, {"idp":1});
      } else {
        emit(doc.date, {"assertion":1});
      }
    } else {
        emit(doc.date, {"fail":1});
    }
  }
}
```

Background info: we process each KPI record to get a listing of "generalProgressSteps" and "newUserSteps". "newUserSteps" identifies a new fallback user (historically, the first graph). The markers to identify general progress through the dialog are here: https://github.com/mozilla/kpi-dashboard/blob/master/server/config/production.json#L44

So the logic here:
- If we don't get to `1 - Dialog shown`, it means it was one of those empty (or nearly empty) blobs, which are hopefully going away.
- If we don't get to `2 - User engaged', it means the user just closed the dialog without doing anything, so we count that as a bounce.
- If we get past the bounce, but an assertion wasn't generated, then we generically call that failure.
- If an assertion is generated, and we have newUserSteps, then its a new fallback user
- If an assertion is generated, and we see `screen.provision_primary_user`, and the new_account flag is true, then we have a new IdP user.
- If the user is not a new fallback or IdP user, then its just a standard successful login (or password reset or add).

This query would allow us to get at the new user bounce rate overall, as well as new IdP users per day.

I was also hoping to have a set of "steps" for new IdP users, as we do for fallback users, which might tweak this query, but the logic would be similar.

So two questions up front:
- can we rely on `new_account` to be accurate?
- is `screen.provision_primary_user` the right event to identify an IdP blob from a fallback blob?

**Comment by kparlante** [comment]
Added IdP cases to existing view in #93
