### ISSUE TITLE
Successful new user signins for IdentityBridging/IdPs

### ISSUE THREAD

**Issue by kparlante** [mozilla/kpi-dashboard#70]
Track new user flow for IdentityBridging/IdPs

**Comment by shane-tomlinson** [comment]
mozilla/browserid#3971 will give us the total number of users who completed signin using a primary. To get only new users, we will have to add different instrumentation to the backend.

**Comment by kparlante** [comment]
@shane-tomlinson : Yeah, I think we're going to want to add different instrumentation to the server for new users, because our fallback counts are likely inaccurate. In terms of bounce rates or trends, it perhaps doesn't matter that much if its not accurate (as long as the trend reflects truth). I do think we benefit from accurate counts of "new users per day" and "active daily users" though.

**Comment by kparlante** [comment]
@shane-tomlinson : Here's my thinking on how to track "new user flow" for IdPs (nothing special for bridging, I'm assuming). 

I think we want to note these milestones (basic stages that the end user is aware of), but I'm open to suggestions:
- 1. Dialog shown (user has opportunity to enter email)
- 2. User directed to IdP
- 3. User back from IdP
- 4. User authenticated successfully

Here is a sample event stream as a new user in a clean browser, first time use of an eyedee.me address:

```
  "event_stream": [
    ["window.dom_loading",322],
    ["xhr_complete.GET/wsapi/session_context",1086,167],
    ["window.channel_established",1271],
    ["screen.rp_info",1272],
    ["screen.authenticate",1277],
    ["user.can_interact",1333],
    ["xhr_complete.GET/wsapi/address_info",20453,712,2],
    ["screen.provision_primary_user",22262],
    ["xhr_complete.GET/wsapi/have_email",22262,168],
    ["screen.verify_primary_user",24153],
    ["window.redirect_to_primary",24154],
    ["window.dom_loading",35563],
    ["xhr_complete.GET/wsapi/session_context",35630,170],
    ["window.channel_established",35834],
    ["screen.rp_info",35835],
    ["screen.provision_primary_user",35840],
    ["xhr_complete.GET/wsapi/have_email",35839,170],
    ["xhr_complete.GET/wsapi/address_info",35842,592],
    ["screen.primary_user_provisioned",37272],
    ["xhr_complete.POST/wsapi/auth_with_assertion",37273,1017],
    ["xhr_complete.GET/wsapi/list_emails",38296,165],
    ["xhr_complete.GET/wsapi/address_info",38465,580],
    ["generate_assertion",39049],
    ["screen.generate_assertion",39050],
    ["assertion_generated",39064],
    ["screen.complete_sign_in",39065]
  ],
  "new_account": true,
  "email_type": "primary",
```
- For 1 (Dialog shown) in the general case, I've been using "screen.rp_info", but was thinking I should change that to "user.can_interact". The idea is to recognize the point where the user gets a dialog but hasn't done anything yet. If they do nothing else (close the dialog at this point), we call it a bounce. This part looks basically the same for all flows.
- For 2 (User directed to IdP) I'm guessing "screen.provision_primary_user" or "screen.verify_primary_user" is the right event -- not clear to me.
- For 3 (User back from IdP) Perhaps "screen.primary_user_provisioned" to indicate that everything succeeded?
- For 4 (User authenticated successfully) Use assertion_generated, as we do with the other flows.

Does that sound reasonable? Should we add other stages? 

FWIW, other event streams…

Here is a sample event stream as a user in a clean browser, but using an eyedee.me address that was used at some other time and place. The event streams look identical, but the KPI data does appear to understand that the account is not new. I don't quite understand how, but JRGM tells me the server is tracking some state about the user/address:

```
  "event_stream": [
    ["window.dom_loading",762],
    ["xhr_complete.GET/wsapi/session_context",1517,168],
    ["window.channel_established",1706],
    ["screen.rp_info",1707],
    ["screen.authenticate",1712],
    ["user.can_interact",1769],
    ["xhr_complete.GET/wsapi/address_info",17962,588,2],
    ["screen.provision_primary_user",19639],
    ["xhr_complete.GET/wsapi/have_email",19639,167],
    ["screen.verify_primary_user",20805],
    ["window.redirect_to_primary",20807],
    ["window.dom_loading",29295],
    ["xhr_complete.GET/wsapi/session_context",29367,170],
    ["window.channel_established",29579],
    ["screen.rp_info",29580],
    ["screen.provision_primary_user",29586],
    ["xhr_complete.GET/wsapi/have_email",29585,167],
    ["xhr_complete.GET/wsapi/address_info",29587,583],
    ["screen.primary_user_provisioned",31210],
    ["xhr_complete.POST/wsapi/auth_with_assertion",31211,596],
    ["xhr_complete.GET/wsapi/list_emails",31813,170],
    ["xhr_complete.GET/wsapi/address_info",31987,591],
    ["generate_assertion",32582],
    ["screen.generate_assertion",32583],
    ["assertion_generated",32597],
    ["screen.complete_sign_in",32598]
  ],
  "new_account": false,
  "email_type": "primary",
```

Here is a sample event stream from an IdP, signing in as an existing user:

```
  "event_stream": [
    ["window.dom_loading",1783],
    ["xhr_complete.GET/wsapi/session_context",3269,169],
    ["window.channel_established",3497],
    ["screen.rp_info",3498],
    ["screen.authenticate",3505],
    ["user.can_interact",3587],
    ["xhr_complete.GET/wsapi/address_info",13751,647,2],
    ["screen.provision_primary_user",15521],
    ["xhr_complete.GET/wsapi/have_email",15520,169],
    ["screen.verify_primary_user",17186],
    ["window.redirect_to_primary",17188],
    ["window.dom_loading",28072],
    ["xhr_complete.GET/wsapi/session_context",28146,170],
    ["window.channel_established",28359],
    ["screen.rp_info",28360],
    ["screen.provision_primary_user",28365],
    ["xhr_complete.GET/wsapi/have_email",28365,171],
    ["xhr_complete.GET/wsapi/address_info",28367,587],
    ["screen.primary_user_provisioned",29817],
    ["xhr_complete.POST/wsapi/auth_with_assertion",29818,600],
    ["xhr_complete.GET/wsapi/list_emails",30423,187],
    ["xhr_complete.GET/wsapi/address_info",30614,564],
    ["generate_assertion",31182],
    ["screen.generate_assertion",31182],
    ["assertion_generated",31198],
    ["screen.complete_sign_in",31199]
  ],
  "new_account": false,
  "email_type": "primary",
```

**Comment by kparlante** [comment]
Added IdP new user signins in #93 -- if we want a full IdP flow add a new bug.
