### ISSUE TITLE
update script falls over when kpiggybank has a lot of data

### ISSUE THREAD

**Issue by kparlante** [mozilla/kpi-dashboard#8]
In the short run, modify the script to take start/end date arguments to fetch slices of data. In the long run, we want to pull only new data.

**Comment by kparlante** [comment]
Update script now only pulls a month's worth of data by default, to avoid this problem. It also accepts timestamp arguments. It needs work beyond this, but that should be tracked in separate issues. Fixed #24.

**Comment by shane-tomlinson** [comment]
When does the update script get run? How do we force kpi-dashboard to get updated data?

**Comment by kparlante** [comment]
The update script gets run manually. The first pass always pulled all data from kpiggybank, which was choking on the hacksign.in instance, which has been collecting data for months now from various dev instances that point at it. This PR got it past that problem, so that we can test it and fix security issues, but clearly we'll need something better: #15
